### ISSUE TITLE
Add the ability to pass PL and LB tags to bwa_mem.pl to perform GTAK's best practices

### ISSUE THREAD

**Issue by jsmedmar** [ICGC-TCGA-PanCancer/PCAP-core#153]
Wondering if it would be possible to pass PL and LB (perhaps other RG tags) to `bwa_mem.pl`

We've been using `bwa_mem.pl` to align our data and this procedure has played well with Sanger pipelines. Recently, we started testing GATK's MUTECT. As per GATK's best practices, alignment post processing is recommended (INDELs Realignment and Base Quality Score Recalibration). To do this, GATK software requires bams to have the `PL` and `LB` bam tags.

Multiple `LB` could be provided (perhaps one per pair of fastq's; one per input bam). I would like to know your thoughts on this.

@zhouyangyu, @mflevine, @juanesarango

**Comment by keiranmraine** [comment]
This version of the repository is under a legacy tag.  New development is on the [cancerit/PCAP-core](https://github.com/cancerit/PCAP-core/) repository and a lot has changed (especially runtime, I/O and working space reductions).  This response refers to the new code base under cancerit.

EDIT: many of those changes look to have been made before we split the repositories.  Bulk of changes are dockstore and job packing for single node execution enhancements in the threaded module.

If you provide a BAM file with valid headers (including LB) then all readgroup information is passed through to the new BAM file (ID may change and SM will reflect the value provided via the `-s` option).  This is true for multi lane BAM and when providing several single lane BAMs.

We are planning to allow users to provide a metadata file so that this can be applied to fastq or BAM files where individual values may be missing.  I've created a [ticket](https://github.com/cancerit/PCAP-core/issues/6).
